name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened ]

jobs:
  goreportcard:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: ./go.mod
    
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.60

    - name: Go Vet
      run: go vet ./...

    - name: Test
      run: go test -v ./...

    - name: Build
      run: go build
